@startuml

title Classes - Class Diagram


class FanState {

    String state;
    void print() { println(state) }

    FanState next();

    FanState previous();
}

FanState <- HeightState
FanState <- LowState
FanState <- MediumState
FanState <- OffState

class CeilingFan  {
    FanState state;

    CeilingFan() {this.state = new OffState();}




    void pullgreen() {this.state = this.state.next() ;  this.state.print()}

     void pullred() {this.state = this.state.previous();this.state.print();}
}



@enduml