@startuml

title "Messages - Sequence Diagram"

actor JuanMosquera #red


Application -> AccountService:1 : deposit()
AccountService ->   AccountDAO : 2 : loadAccount()
AccountService ->   Account : 3 : deposit()
AccountService ->   AccountDAO : 5 : updateAccount()

AccountService ->   AccountService : 6 : refreshInterest()
AccountService ->   Account : 6.1 : addInterest()
Account ->   AccountStrategy : 6.1.1 : addInterest(account.getBalance())
AccountStrategy ->   Account : 6.1.1.1 : (return double % interest)
AccountStrategy ->   AccountCheckingStrategyImpl : 6.1.1.1.1 : addInterest(account.getBalance())
AccountStrategy ->   AccountSavingStrategyImpl : 6.1.1.1.2 : addInterest(account.getBalance())






@enduml